# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-19 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('port', models.SmallIntegerField()),
                ('username', models.CharField(max_length=32)),
                ('passwd', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'hosts',
            },
        ),
    ]
