# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-03 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='cpu',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='hosts',
            name='hostname',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='hosts',
            name='mem',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='hosts',
            name='state',
            field=models.CharField(default='no', max_length=32),
        ),
    ]
