# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-03 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_auto_20170603_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='state',
            field=models.CharField(blank=True, default='no', max_length=32),
        ),
    ]
