# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-17 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('install', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='installmodels',
            table='installModels',
        ),
    ]
