# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-20 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('install', '0003_auto_20170620_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmodels',
            name='tarFile',
            field=models.FileField(upload_to='/Users/hujie2/Documents/workspace/MyCMDB/ansible/'),
        ),
    ]
